"use client";

import { createColumnHelper } from "@tanstack/react-table";
import { DataTable } from "@/components/data/data-table";
import { EmptyState } from "@/components/feedback/empty-state";
import { StatusBadge } from "@/components/feedback/status-badge";
import { PageShell } from "@/components/foundation/page-shell";
import { useAccountingJournals } from "@/features/accounting/use-accounting-module";
import type { AccountingJournalRecord } from "@/types/accounting";

const columnHelper = createColumnHelper<AccountingJournalRecord>();

function toDateInput(value: string) {
  return value.slice(0, 10);
}

export default function AccountingJournalsPage() {
  const journalsQuery = useAccountingJournals();

  const columns = [
    columnHelper.accessor("transaction_date", {
      header: "Date",
      cell: (info) => toDateInput(info.getValue()),
    }),
    columnHelper.accessor("reference_type", {
      header: "Reference Type",
      cell: (info) => <StatusBadge label={info.getValue()} tone="info" />,
    }),
    columnHelper.accessor("reference_id", {
      header: "Reference",
      cell: (info) => info.getValue() ?? "-",
    }),
    columnHelper.accessor("description", { header: "Description" }),
    columnHelper.accessor("line_count", {
      header: "Lines",
      cell: (info) => <StatusBadge label={String(info.getValue())} tone="neutral" />,
    }),
    columnHelper.accessor("total_debit", { header: "Total Debit" }),
    columnHelper.accessor("total_credit", { header: "Total Credit" }),
  ];

  return (
    <PageShell
      eyebrow="Accounting"
      title="Journals"
      description="Review journal headers already generated by the current system without changing posting behavior."
    >
      {journalsQuery.isError ? (
        <EmptyState title="Failed to load journals" description={journalsQuery.error.message} />
      ) : (
        <DataTable columns={columns} data={journalsQuery.data ?? []} emptyMessage="No journals found." />
      )}
    </PageShell>
  );
}
