"use client";

import { createColumnHelper } from "@tanstack/react-table";
import { DataTable } from "@/components/data/data-table";
import { StatusBadge } from "@/components/feedback/status-badge";
import { PageShell } from "@/components/foundation/page-shell";
import { useWarehouseStockBalances } from "@/features/warehouse/use-warehouse-module";
import type { StockBalanceRecord } from "@/types/warehouse";

const columnHelper = createColumnHelper<StockBalanceRecord>();

export default function WarehouseStockBalancesPage() {
  const stockBalancesQuery = useWarehouseStockBalances();

  const columns = [
    columnHelper.accessor("inv_code", {
      header: "Inventory",
      cell: (info) => (
        <div>
          <p className="font-medium">{info.getValue()}</p>
          <p className="text-xs text-muted-foreground">{info.row.original.master_inventory?.inv_name ?? ""}</p>
        </div>
      ),
    }),
    columnHelper.accessor("qty_on_hand", {
      header: "On Hand",
      cell: (info) => (
        <StatusBadge
          label={String(info.getValue())}
          tone={info.getValue() > 0 ? "success" : info.getValue() < 0 ? "danger" : "neutral"}
        />
      ),
    }),
    columnHelper.accessor("master_inventory", {
      header: "HPP",
      cell: (info) => info.getValue()?.hpp ?? "-",
    }),
    columnHelper.accessor("last_updated", {
      header: "Last Updated",
      cell: (info) => new Date(info.getValue()).toLocaleString("en-US"),
    }),
  ];

  return (
    <PageShell
      eyebrow="Warehouse"
      title="Stock Balances"
      description="Review current on-hand inventory balances generated by the existing warehouse stock ledger."
    >
      <DataTable columns={columns} data={stockBalancesQuery.data ?? []} emptyMessage="No stock balances yet." />
    </PageShell>
  );
}
