"use client";

import { createColumnHelper } from "@tanstack/react-table";
import { DataTable } from "@/components/data/data-table";
import { StatusBadge } from "@/components/feedback/status-badge";
import { PageShell } from "@/components/foundation/page-shell";
import { movementTone, toDateInput, useWarehouseStockMovements } from "@/features/warehouse/use-warehouse-module";
import type { StockMovementRecord } from "@/types/warehouse";

const columnHelper = createColumnHelper<StockMovementRecord>();

export default function WarehouseStockMovementsPage() {
  const stockMovementsQuery = useWarehouseStockMovements();

  const columns = [
    columnHelper.accessor("movement_date", {
      header: "Date",
      cell: (info) => toDateInput(info.getValue()),
    }),
    columnHelper.accessor("inv_code", {
      header: "Inventory",
      cell: (info) => (
        <div>
          <p className="font-medium">{info.getValue()}</p>
          <p className="text-xs text-muted-foreground">{info.row.original.master_inventory?.inv_name ?? ""}</p>
        </div>
      ),
    }),
    columnHelper.accessor("reference_type", {
      header: "Source",
      cell: (info) => <StatusBadge label={info.getValue()} tone={movementTone(info.getValue())} />,
    }),
    columnHelper.accessor("reference_id", {
      header: "Reference",
      cell: (info) => <span className="font-mono text-xs">{info.getValue()}</span>,
    }),
    columnHelper.accessor("qty_change", {
      header: "Change",
      cell: (info) => (
        <span className={info.getValue() >= 0 ? "text-emerald-700" : "text-amber-700"}>
          {info.getValue() > 0 ? `+${info.getValue()}` : info.getValue()}
        </span>
      ),
    }),
    columnHelper.accessor("running_balance", { header: "Running" }),
    columnHelper.accessor("notes", {
      header: "Notes",
      cell: (info) => info.getValue() ?? "-",
    }),
  ];

  return (
    <PageShell
      eyebrow="Warehouse"
      title="Stock Movements"
      description="Review the movement ledger generated by inbound, adjustment, and sales stock activity."
    >
      <DataTable columns={columns} data={stockMovementsQuery.data ?? []} emptyMessage="No stock movements yet." />
    </PageShell>
  );
}
